"""undoing relationships for now

Revision ID: 096007aa0ef6
Revises: b6d2be30fed5
Create Date: 2024-03-10 16:21:21.405558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096007aa0ef6'
down_revision = 'b6d2be30fed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_category',
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gear_categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['gear_item.id'], )
    )
    # ### end Alembic commands ###
