"""making many to many relationship for days and classes

Revision ID: 10b5a3e8854d
Revises: 259edeb85b4a
Create Date: 2024-04-05 16:22:22.541978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b5a3e8854d'
down_revision = '259edeb85b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_days_ref',
    sa.Column('classes_id', sa.Integer(), nullable=True),
    sa.Column('days_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classes_id'], ['days_of_week.id'], ),
    sa.ForeignKeyConstraint(['days_id'], ['classes.id'], )
    )
    op.drop_table('_alembic_tmp_classes')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_classes_create_date'), ['create_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_start_date'), ['start_date'], unique=False)

    with op.batch_alter_table('days_of_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_days_of_week_classes_id', 'classes', ['classes_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_of_week', schema=None) as batch_op:
        batch_op.drop_constraint('fk_days_of_week_classes_id', type_='foreignkey')
        batch_op.drop_column('classes_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_start_date'))
        batch_op.drop_index(batch_op.f('ix_classes_end_date'))
        batch_op.drop_index(batch_op.f('ix_classes_create_date'))
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)

    op.create_table('_alembic_tmp_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=180), nullable=False),
    sa.Column('morning', sa.BOOLEAN(), nullable=False),
    sa.Column('afternoon', sa.BOOLEAN(), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('create_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('classes_days_ref')
    # ### end Alembic commands ###
