"""adding qty to items

Revision ID: 20389d8b0dee
Revises: 2f33701d68bf
Create Date: 2024-05-30 10:39:59.740207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20389d8b0dee'
down_revision = '2f33701d68bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_column('qty')

    # ### end Alembic commands ###
