"""moving days to separate table

Revision ID: 259edeb85b4a
Revises: 4d8c7ba637e5
Create Date: 2024-04-04 21:38:23.610883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259edeb85b4a'
down_revision = '4d8c7ba637e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('days_of_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('mon')
        batch_op.drop_column('thu')
        batch_op.drop_column('wed')
        batch_op.drop_column('fri')
        batch_op.drop_column('tue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tue', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('fri', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('wed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('thu', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('mon', sa.BOOLEAN(), nullable=False))

    op.drop_table('days_of_week')
    # ### end Alembic commands ###
