"""making create dates and last login non-nullable

Revision ID: 27be5c7b1214
Revises: af26c648313a
Create Date: 2024-04-23 07:58:38.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27be5c7b1214'
down_revision = 'af26c648313a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('create_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_login',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_last_login'), ['last_login'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_login'))
        batch_op.alter_column('last_login',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('create_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
