"""adding qty available and qty out to gear model

Revision ID: 2f33701d68bf
Revises: 4bda10620a48
Create Date: 2024-05-30 10:32:54.242707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f33701d68bf'
down_revision = '4bda10620a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_gear_item')
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qty_out', sa.Integer(), nullable=True))
        batch_op.drop_column('qty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty', sa.INTEGER(), nullable=False))
        batch_op.drop_column('qty_out')
        batch_op.drop_column('qty_available')

    op.create_table('_alembic_tmp_gear_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('image', sa.VARCHAR(length=256), nullable=True),
    sa.Column('care_instructions', sa.TEXT(), nullable=True),
    sa.Column('img_thumb', sa.VARCHAR(length=256), nullable=True),
    sa.Column('qty_available', sa.INTEGER(), nullable=False),
    sa.Column('qty_out', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
