"""hoping

Revision ID: 3411edad3ebc
Revises: 6b0bc365ab09
Create Date: 2024-03-09 22:15:50.203204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3411edad3ebc'
down_revision = '6b0bc365ab09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gear_item_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_item_name'))

    op.drop_table('gear_item')
    # ### end Alembic commands ###
