"""making last mod date non-nullable on student model

Revision ID: 4bda10620a48
Revises: 718198168ae6
Create Date: 2024-05-11 11:49:27.386734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bda10620a48'
down_revision = '718198168ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('last_modified',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('last_modified',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
