"""removing nullable options

Revision ID: 4d8c59a4e917
Revises: 31c984cb6418
Create Date: 2024-04-04 10:37:41.469045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8c59a4e917'
down_revision = '31c984cb6418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('monday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('tuesday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('wednesday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('thursday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('friday',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('morning',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('afternoon',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('afternoon',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('morning',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('friday',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('thursday',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('wednesday',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('tuesday',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('monday',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
