"""fine tuning relationship

Revision ID: 4ecaee4d45b6
Revises: 10b5a3e8854d
Create Date: 2024-04-06 15:45:41.723465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecaee4d45b6'
down_revision = '10b5a3e8854d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_of_week', schema=None) as batch_op:
        batch_op.drop_constraint('fk_days_of_week_classes_id', type_='foreignkey')
        batch_op.drop_column('classes_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('days_of_week', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classes_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_days_of_week_classes_id', 'classes', ['classes_id'], ['id'])

    # ### end Alembic commands ###
