"""looking promising

Revision ID: 579c8f0791a2
Revises: 3411edad3ebc
Create Date: 2024-03-09 22:21:21.899215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579c8f0791a2'
down_revision = '3411edad3ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('gear_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gear_item.id'], ),
    sa.ForeignKeyConstraint(['gear_id'], ['gear_categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'gear_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear_category')
    # ### end Alembic commands ###
