"""adding last mod date to student model

Revision ID: 718198168ae6
Revises: 27be5c7b1214
Create Date: 2024-05-11 11:41:31.991582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718198168ae6'
down_revision = '27be5c7b1214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_last_modified'), ['last_modified'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_last_modified'))
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
