"""making category names unique

Revision ID: 7d60cc21cacd
Revises: f6c0ea619587
Create Date: 2024-03-11 10:01:18.388773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d60cc21cacd'
down_revision = 'f6c0ea619587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_gear_categories_name')
        batch_op.create_index(batch_op.f('ix_gear_categories_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_categories_name'))
        batch_op.create_index('ix_gear_categories_name', ['name'], unique=False)

    # ### end Alembic commands ###
