"""adding create date and last modified date to user model

Revision ID: 9f4cef0419a0
Revises: 0eca3a624a29
Create Date: 2024-04-23 07:10:23.936001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4cef0419a0'
down_revision = '0eca3a624a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_modified', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_create_date'), ['create_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_create_date'))
        batch_op.drop_column('last_modified')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
