"""renaming last_modified to last_login in user model

Revision ID: af26c648313a
Revises: 9f4cef0419a0
Create Date: 2024-04-23 07:16:09.337964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af26c648313a'
down_revision = '9f4cef0419a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.Date(), nullable=True))
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DATE(), nullable=True))
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
