"""renaming days of the week

Revision ID: b4d7a571f003
Revises: 560f51c933fc
Create Date: 2024-04-04 16:00:06.263282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d7a571f003'
down_revision = '560f51c933fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mon', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('tue', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('wed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('thur', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fri', sa.Boolean(), nullable=False))
        batch_op.drop_column('monday')
        batch_op.drop_column('tuesday')
        batch_op.drop_column('friday')
        batch_op.drop_column('thursday')
        batch_op.drop_column('wednesday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wednesday', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('thursday', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('friday', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('tuesday', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('monday', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('fri')
        batch_op.drop_column('thur')
        batch_op.drop_column('wed')
        batch_op.drop_column('tue')
        batch_op.drop_column('mon')

    # ### end Alembic commands ###
