"""new migrations

Revision ID: b6d2be30fed5
Revises: 
Create Date: 2024-03-10 16:19:23.734690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d2be30fed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('care_instructions', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gear_item_name'), ['name'], unique=False)

    op.create_table('gear_category',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gear_categories.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['gear_item.id'], )
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index('ix_classes_name')

    op.drop_table('classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index('ix_classes_name', ['name'], unique=False)

    op.drop_table('gear_category')
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_item_name'))

    op.drop_table('gear_item')
    # ### end Alembic commands ###
