"""making item names unique

Revision ID: eed70b6b0bea
Revises: 7d60cc21cacd
Create Date: 2024-03-16 21:09:09.349756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed70b6b0bea'
down_revision = '7d60cc21cacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_index('ix_gear_item_name')
        batch_op.create_index(batch_op.f('ix_gear_item_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_item_name'))
        batch_op.create_index('ix_gear_item_name', ['name'], unique=False)

    # ### end Alembic commands ###
