"""testing

Revision ID: f6c0ea619587
Revises: 096007aa0ef6
Create Date: 2024-03-10 17:02:08.823653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c0ea619587'
down_revision = '096007aa0ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear_categories_ref',
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gear_item.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['gear_categories.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear_categories_ref')
    # ### end Alembic commands ###
