"""adding thumbnail path to item model

Revision ID: fe6310f486cd
Revises: eed70b6b0bea
Create Date: 2024-03-16 22:05:28.186550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6310f486cd'
down_revision = 'eed70b6b0bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_thumb', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear_item', schema=None) as batch_op:
        batch_op.drop_column('img_thumb')

    # ### end Alembic commands ###
